version: '3.8'

services:
  web:
    image: python:3.11-slim  # Use the official Python image
    container_name: library_app
    working_dir: /app
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./bookflix:/app/bookflix  # Mount the current directory to /app inside the container
      - /app/bookflix/__pycache__  # Exclude __pycache__ from being copied to host
      - /app/venv  # Exclude venv directory
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    environment:
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing .pyc files
      - PYTHONUNBUFFERED=1  # Ensures output is displayed in the console in real-time
    command: bash -c "apt update && apt install -y zbar-tools && pip install --upgrade -r requirements.txt && fastapi dev --help && fastapi dev --host 0.0.0.0 bookflix/main.py"

