services:
  bookflix:
    image: python:3.11-slim  # Use the official Python image
    working_dir: /app
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./bookflix:/app/bookflix  # Mount the current directory to /app inside the container
      - ./library.db:/app/library.db # sqlite
      - /app/bookflix/__pycache__  # Exclude __pycache__ from being copied to host
      - /app/venv  # Exclude venv directory
    ports:
      - "8000"  # Map port 8000 on the host to port 8000 in the container
    environment:
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing .pyc files
      - PYTHONUNBUFFERED=1  # Ensures output is displayed in the console in real-time
      - GOOGLE_BOOKS_API_KEY=AIzaSyCJUtnv4PzBPzjOAvrtHthLOwGY7wC30oY
    command: bash -c "pip install --upgrade -r requirements.txt && fastapi dev --help && fastapi dev --host 0.0.0.0 bookflix/main.py"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bookflix.loadbalancer.server.port=8000"
      - "traefik.http.routers.bookflix.rule=Host(`bookflix.vermeille.fr`)"
      - "traefik.http.routers.bookflix.tls=true"
      - "traefik.http.routers.bookflix.tls.certresolver=letsencrypt"
